name: Metrics
on: 
  schedule:
    - cron: '0 0/3 * * *'
  workflow_dispatch: 
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrci1 
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics1.svg
          user: lavitalite
          base: ""
          config_timezone: Asia/Chongqing
          config_twemoji: yes
          repositories_skipped: node_farm
          use_prebuilt_image: yes

          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_havits_days: yes
          plugin_habits_facts: yes
          plugin_habits_from: 200

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_ignored: deployer, gister,automator

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
        
    
